;;; my-consult-http-things.el --- HTTP things with consult -*- lexical-binding: t; -*-
;;; Commentary:

;;; Code:

(use-package consult :ensure t)

(defconst http-status
  '(("CONTINUE" ("100" "indicates that the initial part of a request has been received and has not yet been rejected by the server."))
    ("SWITCHING_PROTOCOLS" ("101" "indicates that the server understands and is willing to comply with the client's request, via the Upgrade header field, for a change in the application protocol being used on this connection."))
    ("OK" ("200" "indicates that the request has succeeded."))
    ("CREATED" ("201" "indicates that the request has been fulfilled and has resulted in one or more new resources being created."))
    ("ACCEPTED" ("202" "indicates that the request has been accepted for processing, but the processing has not been completed."))
    ("NON_AUTHORITATIVE_INFORMATION" ("203" "indicates that the request was successful but the enclosed payload has been modified from that of the origin server's 200 (OK) response by a transforming proxy."))
    ("NO_CONTENT" ("204" "indicates that the server has successfully fulfilled the request and that there is no additional content to send in the response payload body."))
    ("RESET_CONTENT" ("205" "indicates that the server has fulfilled the request and desires that the user agent reset the document view, which caused the request to be sent, to its original state as received from the origin server."))
    ("PARTIAL_CONTENT" ("206" "indicates that the server is successfully fulfilling a range request for the target resource by transferring one or more parts of the selected representation that correspond to the satisfiable ranges found in the requests's Range header field."))
    ("MULTIPLE_CHOICES" ("300" "indicates that the target resource has more than one representation, each with its own more specific identifier, and information about the alternatives is being provided so that the user (or user agent) can select a preferred representation by redirecting its request to one or more of those identifiers."))
    ("MOVED_PERMANENTLY" ("301" "indicates that the target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs."))
    ("FOUND" ("302" "indicates that the target resource resides temporarily under a different URI."))
    ("SEE_OTHER" ("303" "indicates that the server is redirecting the user agent to a different resource, as indicated by a URI in the Location header field, that is intended to provide an indirect response to the original request."))
    ("NOT_MODIFIED" ("304" "indicates that a conditional GET request has been received and would have resulted in a 200 (OK) response if it were not for the fact that the condition has evaluated to false."))
    ("USE_PROXY" ("305" "*deprecated*"))
    ("TEMPORARY_REDIRECT" ("307" "indicates that the target resource resides temporarily under a different URI and the user agent MUST NOT change the request method if it performs an automatic redirection to that URI."))
    ("BAD_REQUEST" ("400" "indicates that the server cannot or will not process the request because the received syntax is invalid, nonsensical, or exceeds some limitation on what the server is willing to process."))
    ("UNAUTHORIZED" ("401" "indicates that the request has not been applied because it lacks valid authentication credentials for the target resource."))
    ("PAYMENT_REQUIRED" ("402" "*reserved*"))
    ("FORBIDDEN" ("403" "indicates that the server understood the request but refuses to authorize it."))
    ("NOT_FOUND" ("404" "indicates that the origin server did not find a current representation for the target resource or is not willing to disclose that one exists."))
    ("METHOD_NOT_ALLOWED" ("405" "indicates that the method specified in the request-line is known by the origin server but not supported by the target resource."))
    ("NOT_ACCEPTABLE" ("406" "indicates that the target resource does not have a current representation that would be acceptable to the user agent, according to the proactive negotiation header fields received in the request, and the server is unwilling to supply a default representation."))
    ("PROXY_AUTHENTICATION_REQUIRED" ("407" "is similar to 401 (Unauthorized), but indicates that the client needs to authenticate itself in order to use a proxy."))
    ("REQUEST_TIMEOUT" ("408" "indicates that the server did not receive a complete request message within the time that it was prepared to wait."))
    ("CONFLICT" ("409" "indicates that the request could not be completed due to a conflict with the current state of the resource."))
    ("GONE" ("410" "indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent."))
    ("LENGTH_REQUIRED" ("411" "indicates that the server refuses to accept the request without a defined Content-Length."))
    ("PRECONDITION_FAILED" ("412" "indicates that one or more preconditions given in the request header fields evaluated to false when tested on the server."))
    ("PAYLOAD_TOO_LARGE" ("413" "indicates that the server is refusing to process a request because the request payload is larger than the server is willing or able to process."))
    ("URI_TOO_LONG" ("414" "indicates that the server is refusing to service the request because the request-target is longer than the server is willing to interpret."))
    ("UNSUPPORTED_MEDIA_TYPE" ("415" "indicates that the origin server is refusing to service the request because the payload is in a format not supported by the target resource for this method."))
    ("RANGE_NOT_SATISFIABLE" ("416" "indicates that none of the ranges in the request's Range header field overlap the current extent of the selected resource or that the set of ranges requested has been rejected due to invalid ranges or an excessive request of small or overlapping ranges."))
    ("EXPECTATION_FAILED" ("417" "indicates that the expectation given in the request's Expect header field could not be met by at least one of the inbound servers."))
    ("I_M_A_TEAPOT" ("418" "Any attempt to brew coffee with a teapot should result in the error code 418 I'm a teapot."))
    ("UPGRADE_REQUIRED" ("426" "indicates that the server refuses to perform the request using the current protocol but might be willing to do so after the client upgrades to a different protocol."))
    ("INTERNAL_SERVER_ERROR" ("500" "indicates that the server encountered an unexpected condition that prevented it from fulfilling the request."))
    ("NOT_IMPLEMENTED" ("501" "indicates that the server does not support the functionality required to fulfill the request."))
    ("BAD_GATEWAY" ("502" "indicates that the server, while acting as a gateway or proxy, received an invalid response from an inbound server it accessed while attempting to fulfill the request."))
    ("SERVICE_UNAVAILABLE" ("503" "indicates that the server is currently unable to handle the request due to a temporary overload or scheduled maintenance, which will likely be alleviated after some delay."))
    ("GATEWAY_TIME_OUT" ("504" "indicates that the server, while acting as a gateway or proxy, did not receive a timely response from an upstream server it needed to access in order to complete the request."))
    ("HTTP_VERSION_NOT_SUPPORTED" ("505" "indicates that the server does not support, or refuses to support, the protocol version that was used in the request message."))
    ("PROCESSING" ("102" "is an interim response used to inform the client that the server has accepted the complete request, but has not yet completed it."))
    ("MULTI_STATUS" ("207" "provides status for multiple independent operations."))
    ("IM_USED" ("226" "The server has fulfilled a GET request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance."))
    ("PERMANENT_REDIRECT" ("308" "The target resource has been assigned a new permanent URI and any future references to this resource outght to use one of the enclosed URIs. [...] This status code is similar to 301 Moved Permanently (Section 7.3.2 of rfc7231), except that it does not allow rewriting the request method from POST to GET."))
    ("UNPROCESSABLE_ENTITY" ("422" "means the server understands the content type of the request entity (hence a 415(Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions."))
    ("LOCKED" ("423" "means the source or destination resource of a method is locked."))
    ("FAILED_DEPENDENCY" ("424" "means that the method could not be performed on the resource because the requested action depended on another action and that action failed."))
    ("PRECONDITION_REQUIRED" ("428" "indicates that the origin server requires the request to be conditional."))
    ("TOO_MANY_REQUESTS" ("429" "indicates that the user has sent too many requests in a given amount of time (rate limiting)."))
    ("REQUEST_HEADER_FIELDS_TOO_LARGE" ("431" "indicates that the server is unwilling to process the request because its header fields are too large."))
    ("UNAVAILABLE_FOR_LEGAL_REASONS" ("451" "This status code indicates that the server is denying access to the resource in response to a legal demand."))
    ("VARIANT_ALSO_NEGOTIATES" ("506" "indicates that the server has an internal configuration error: the chosen variant resource is configured to engage in transparent content negotiation itself, and is therefore not a proper end point in the negotiation process."))
    ("INSUFFICIENT_STORAGE" ("507" "means the method could not be performed on the resource because the server is unable to store the representation needed to successfully complete the request."))
    ("NETWORK_AUTHENTICATION_REQUIRED" ("511" "indicates that the client needs to authenticate to gain network access."))))

(defconst http-headers
  '(("content-encoding" ("indicates what content codings have been applied to the representation, beyond those inherent in the media type, and thus what decoding mechanisms have to be applied in order to obtain data in the media type referenced by the Content-Type header field."))
    ("content-language" ("describes the natural language(s) of the intended audience for the representation."))
    ("content-location" ("references a URI that can be used as an identifier for a specific resource corresponding to the representation in this message's payload."))
    ("content-type" ("indicates the media type of the associated representation: either the representation enclosed in the message payload or the selected representation, as determined by the message semantics."))
    ("content-length" ("can provide the anticipated size, as a decimal number of octets, for a potential payload body."))
    ("content-range" ("is sent in a single part 206 (Partial Content) response to indicate the partial range of the selected representation enclosed as the message payload, sent in each part of a multipart 206 response to indicate the range enclosed within each body part, and sent in 416 (Range Not Satisfiable) responses to provide information about the selected representation."))
    ("transfer-encoding" ("lists the transfer coding names corresponding to the sequence of transfer codings that have been (or will be) applied to the payload body in order to form the message body."))
    ("cache-control" ("is used to specify directives for caches along the request/response chain."))
    ("expect" ("is used to indicate that particular server behaviors are required by the client."))
    ("host" ("provides the host and port information from the target URI, enabling the origin server to distinguish among resources while servicing requests for multiple host names on a single IP address."))
    ("max-forwards" ("provides a mechanism with the TRACE and OPTIONS methods to limit the number of times that the request is forwarded by proxies."))
    ("pragma" ("allows backwards compatibility with HTTP/1.0 caches, so that clients can specify a no-cache request that they will understand (as Cache-Control was not defined until HTTP/1.1)."))
    ("range" ("modifies the method semantics to request transfer of only one or more subranges of the selected representation data, rather than the entire selected representation data."))
    ("te" ("indicates what transfer codings, besides chunked, the client is willing to accept in response, and whether or not the client is willing to accept trailer fields in a chunked transfer coding."))
    ("if-match" ("can be used to make a request method conditional on the current existence or value of an entity-tag for one or more representations of the target resource."))
    ("if-modified-since" ("can be used with GET or HEAD to make the method conditional by modification date: if the selected representation has not been modified since the time specified in this field, then do not perform the request method; instead, respond as detailed below."))
    ("if-none-match" ("can be used to make a request method conditional on not matching any of the current entity-tag values for representations of the target resource."))
    ("if-range" ("Informally, its meaning is: if the representation is unchanged, send me the part(s) that I am requesting in Range; otherwise, send me the entire representation."))
    ("if-unmodified-since" ("can be used to make a request method conditional by modification date: if the selected representation has been modified since the time specified in this field, then the server MUST NOT perform the requested operation and MUST instead respond with the 412 (Precondition Failed) status code."))
    ("accept" ("can be used to specify certain media types which are acceptable for the response."))
    ("accept-charset" ("can be sent by a user agent to indicate what charsets are acceptable in textual response content."))
    ("accept-encoding" ("can be used by user agents to indicate what response content-codings are acceptable in the response."))
    ("accept-language" ("can be used by user agents to indicate the set of natural languages that are preferred in the response."))
    ("authorization" ("allows a user agent to authenticate itself with a server -- usually, but not necessarily, after receiving a 401 (Unauthorized) response."))
    ("proxy-authorization" ("allows the client to identify itself (or its user) to a proxy that requires authentication."))
    ("dnt" ("defined as the means for expressing a user's tracking preference via HTTP."))
    ("from" ("contains an Internet email address for a human user who controls the requesting user agent."))
    ("referer" ("allows the user agent to specify a URI reference for the resource from which the target URI was obtained (i.e., the referrer, though the field name is misspelled)."))
    ("user-agent" ("contains information about the user agent originating the request, which is often used by servers to help identify the scope of reported interoperability problems, to work around or tailor responses to avoid particular user agent limitations, and for analytics regarding browser or operating system use."))
    ("age" ("conveys the sender's estimate of the amount of time since the response was generated or successfully validated at the origin server."))
    ("cache-control" ("is used to specify directives for caches along the request/response chain."))
    ("expires" ("gives the date/time after which the response is considered stale."))
    ("date" ("represents the date and time at which the message was originated"))
    ("location" ("is used in some responses to refer to a specific resource in relation to the response."))
    ("retry-after" ("indicates how long the user agent ought to wait before making a follow-up request."))
    ("tk" ("defined as an OPTIONAL means for indicating the tracking status that applied to the corresponding request and as a REQUIRED means for indicating that a state-changing request has resulted in an interactive change to the tracking status. "))
    ("vary" ("describes what parts of a request message, aside from the method and request target, might influence the origin server's process for selecting and representing the response."))
    ("warning" ("is used to carry additional information about the status or transformation of a message that might not be reflected in the message."))
    ("etag" ("provides the current entity-tag for the selected representation, as determined at the conclusion of handling the request."))
    ("last-modified" ("provides a timestamp indicating the date and time at which the origin server believes the selected representation was last modified, as determined at the conclusion of handling the request."))
    ("www-authenticate" ("consists of at least one challenge that indicates the authentication scheme(s) and parameters applicable to the effective request URI."))
    ("proxy-authenticate" ("consists of at least one challenge that indicates the authentication scheme(s) and parameters applicable to the proxy for this effective request URI."))
    ("accept-ranges" ("allows a server to indicate that it supports range requests for the target resource."))
    ("allow" ("lists the set of methods advertised as supported by the target resource."))
    ("server" ("contains information about the software used by the origin server to handle the request, which is often used by clients to help identify the scope of reported interoperability problems, to work around or tailor requests to avoid particular server limitations, and for analytics regarding server or operating system use."))
    ("accept-patch" ("used to specify the patch document formats accepted by the server."))
    ("accept-post" ("indicates server support for specific media types for entity bodies in HTTP POST requests."))
    ("access-control-allow-credentials" ("indicates whether the response to request can be exposed when the omit credentials flag is unset"))
    ("access-control-allow-headers" ("indicates, as part of the response to a preflight request, which header field names can be used during the actual request"))
    ("access-control-allow-methods" ("indicates, as part of the response to a preflight request, which methods can be used during the actual request"))
    ("access-control-allow-origin" ("indicates whether a resource can be shared"))
    ("access-control-expose-headers" ("indicates which headers are safe to expose to the API of a CORS API specification"))
    ("access-control-max-age" ("indicates how long the results of a preflight request can be cached in a preflight result cache"))
    ("access-control-request-headers" ("indicates which headers will be used in the actual request as part of the preflight request"))
    ("access-control-request-method" ("indicates which method will be used in the actual request as part of the preflight request"))
    ("content-disposition" ("standard"))
    ("content-security-policy" ("is the preferred mechanism for delivering a CSP policy"))
    ("content-security-policy-report-only" ("lets servers experiment with policies by monitoring (rather than enforcing) a policy"))
    ("cookie" ("standard"))
    ("forwarded" ("standard"))
    ("link" ("provides a means for serialising one or more links in HTTP headers."))
    ("origin" ("standard"))
    ("prefer" ("is used to indicate that particular server behaviors are preferred by the client, but not required for successful completion of the request."))
    ("preference-applied" ("MAY be included within a response message as an indication as to which Prefer tokens were honored by the server and applied to the processing of a request."))
    ("set-cookie" ("standard"))
    ("strict-transport-security" ("standard"))
    ("accept-ch" ("advertise support for Client Hints"))
    ("accept-features" ("can be used by a user agent to give information about the presence or absence of certain features in the feature set of the current request."))
    ("alpn" ("indicates the application-layer protocol that a client intends to use within the tunnel, or a set of protocols that might be used within the tunnel."))
    ("alt-svc" ("is advertising the availability of alternate services to HTTP/1.1 and HTTP/2.0 clients by adding an Alt-Svc header field to responses."))
    ("alternates" ("is used to convey the list of variants bound to a negotiable resource."))
    ("ch" ("describes an example list of client preferences that the server can use to adapt and optimize the resource to satisfy a given request."))
    ("content-base" ("obsoleted"))
    ("content-dpr" ("is a number that indicates the ratio between physical pixels over CSS px of the selected image response."))
    ("dasl" ("standard"))
    ("dav" ("standard"))
    ("depth" ("standard"))
    ("destination" ("standard"))
    ("dpr" ("is a number that, in requests, indicates the client’s current Device Pixel Ratio (DPR), which is the ratio of physical pixels over CSS px of the layout viewport on the device."))
    ("encryption" ("describes the encrypted content encoding(s) that have been applied to a payload body, and therefore how those content encoding(s) can be removed."))
    ("encryption-key" ("can be used to describe the input keying material used in the Encryption header field."))
    ("if" ("standard"))
    ("if-schedule-tag-match" ("standard"))
    ("key" ("allows an origin server to describe the cache key for a negotiated response: a short algorithm that can be used upon later requests to determine if the same response is reusable."))
    ("last-event-id" ("The value of the event source's last event ID string, encoded as UTF-8."))
    ("link-template" ("provides a means for serialising one or more links into HTTP headers."))
    ("lock-token" ("standard"))
    ("md" ("is a number that, in requests, indicates the client’s maximum downlink speed in megabits per second (Mbps), which is the standardized, or generally accepted, maximum download data rate for the underlying connection technology in use by the client."))
    ("negotiate" ("can contain directives for any content negotiation process initiated by the request."))
    ("nice" ("indicates that a request is less important than a request that doesn't bear this header."))
    ("ordering-type" ("standard"))
    ("overwrite" ("standard"))
    ("poe" ("The POE HTTP header is a request-header field whose field-value indicates the version of POE that a client supports."))
    ("poe-links" ("The POE-Links HTTP header is an entity-header field whose field-value is a comma-separated list of quoted URI-references (without fragment identifiers) that the origin server asserts to be POE resources. The contents of the POE-Links response header SHOULD correspond to links found in the content of the response body."))
    ("position" ("standard"))
    ("rw" ("is a number that, in requests, indicates the Resource Width (RW) in CSS px, which is either the display width of the requested resource (e.g. display width of an image), or the layout viewport width if the resource does not have a display width (e.g. a non-image asset)."))
    ("schedule-reply" ("standard"))
    ("schedule-tag" ("standard"))
    ("sec-websocket-accept" ("standard"))
    ("sec-websocket-extensions" ("standard"))
    ("sec-websocket-key" ("standard"))
    ("sec-websocket-protocol" ("standard"))
    ("sec-websocket-version" ("standard"))
    ("slug" ("standard"))
    ("sunset" ("allows a server to communicate the fact that a resource is expected to become unresponsive at a specific point in time."))
    ("tcn" ("is used by a server to signal that the resource is transparently negotiated."))
    ("timeout" ("standard"))
    ("variant-vary" ("can be used in a choice response to record any vary information which applies to the variant data (the entity body combined with some of the entity headers) contained in the response, rather than to the response as a whole."))
    ("x-frame-options" ("indicates a policy that specifies whether the browser should render the transmitted resource within a &lt;frame&gt; or an &lt;iframe&gt;. Servers can declare this policy in the header of their HTTP responses to prevent clickjacking attacks, which ensures that their content is not embedded into other pages or frames."))))

(defconst media-types
  '(("application/1d-interleaved-parityfec" ("https://www.iana.org/assignments/media-types/application/1d-interleaved-parityfec"))
    ("application/a2l" ("https://www.iana.org/assignments/media-types/application/A2L"))
    ("application/activemessage" ("https://www.iana.org/assignments/media-types/application/activemessage"))
    ("application/activemessage" ("https://www.iana.org/assignments/media-types/application/activemessage"))
    ("application/aml" ("https://www.iana.org/assignments/media-types/application/AML"))
    ("application/andrew-inset" ("https://www.iana.org/assignments/media-types/application/andrew-inset"))
    ("application/applefile" ("https://www.iana.org/assignments/media-types/application/applefile"))
    ("application/atf" ("https://www.iana.org/assignments/media-types/application/ATF"))
    ("application/atfx" ("https://www.iana.org/assignments/media-types/application/ATFX"))
    ("application/atomicmail" ("https://www.iana.org/assignments/media-types/application/atomicmail"))
    ("application/atxml" ("https://www.iana.org/assignments/media-types/application/ATXML"))
    ("application/batch-smtp" ("https://www.iana.org/assignments/media-types/application/batch-SMTP"))
    ("application/call-completion" ("https://www.iana.org/assignments/media-types/application/call-completion"))
    ("application/cals-1840" ("https://www.iana.org/assignments/media-types/application/CALS-1840"))
    ("application/cbor" ("https://www.iana.org/assignments/media-types/application/cbor"))
    ("application/cdmi-capability" ("https://www.iana.org/assignments/media-types/application/cdmi-capability"))
    ("application/cdmi-container" ("https://www.iana.org/assignments/media-types/application/cdmi-container"))
    ("application/cdmi-domain" ("https://www.iana.org/assignments/media-types/application/cdmi-domain"))
    ("application/cdmi-object" ("https://www.iana.org/assignments/media-types/application/cdmi-object"))
    ("application/cdmi-queue" ("https://www.iana.org/assignments/media-types/application/cdmi-queue"))
    ("application/cdni" ("https://www.iana.org/assignments/media-types/application/cdni"))
    ("application/cea" ("https://www.iana.org/assignments/media-types/application/CEA"))
    ("application/cfw" ("https://www.iana.org/assignments/media-types/application/cfw"))
    ("application/cms" ("https://www.iana.org/assignments/media-types/application/cms"))
    ("application/commonground" ("https://www.iana.org/assignments/media-types/application/commonground"))
    ("application/csrattrs" ("https://www.iana.org/assignments/media-types/application/csrattrs"))
    ("application/cybercash" ("https://www.iana.org/assignments/media-types/application/cybercash"))
    ("application/dashdelta" ("https://www.iana.org/assignments/media-types/application/dashdelta"))
    ("application/dca-rft" ("https://www.iana.org/assignments/media-types/application/dca-rft"))
    ("application/dcd" ("https://www.iana.org/assignments/media-types/application/DCD"))
    ("application/dec-dx" ("https://www.iana.org/assignments/media-types/application/dec-dx"))
    ("application/dicom" ("https://www.iana.org/assignments/media-types/application/dicom"))
    ("application/dii" ("https://www.iana.org/assignments/media-types/application/DII"))
    ("application/dit" ("https://www.iana.org/assignments/media-types/application/DIT"))
    ("application/dns" ("https://www.iana.org/assignments/media-types/application/dns"))
    ("application/dvcs" ("https://www.iana.org/assignments/media-types/application/dvcs"))
    ("application/ecmascript" ("https://www.iana.org/assignments/media-types/application/ecmascript"))
    ("application/edi-consent" ("https://www.iana.org/assignments/media-types/application/EDI-consent"))
    ("application/edifact" ("https://www.iana.org/assignments/media-types/application/EDIFACT"))
    ("application/edi-x12" ("https://www.iana.org/assignments/media-types/application/EDI-X12"))
    ("application/encaprtp" ("https://www.iana.org/assignments/media-types/application/encaprtp"))
    ("application/eshop" ("https://www.iana.org/assignments/media-types/application/eshop"))
    ("application/example" ("https://www.iana.org/assignments/media-types/application/example"))
    ("application/fastinfoset" ("https://www.iana.org/assignments/media-types/application/fastinfoset"))
    ("application/fastsoap" ("https://www.iana.org/assignments/media-types/application/fastsoap"))
    ("application/fits" ("https://www.iana.org/assignments/media-types/application/fits"))
    ("application/font-sfnt" ("https://www.iana.org/assignments/media-types/application/font-sfnt"))
    ("application/font-tdpfr" ("https://www.iana.org/assignments/media-types/application/font-tdpfr"))
    ("application/font-woff" ("https://www.iana.org/assignments/media-types/application/font-woff"))
    ("application/gzip" ("https://www.iana.org/assignments/media-types/application/gzip"))
    ("application/h224" ("https://www.iana.org/assignments/media-types/application/H224"))
    ("application/http" ("https://www.iana.org/assignments/media-types/application/http"))
    ("application/hyperstudio" ("https://www.iana.org/assignments/media-types/application/hyperstudio"))
    ("application/ibe-pp-data" ("https://www.iana.org/assignments/media-types/application/ibe-pp-data"))
    ("application/iges" ("https://www.iana.org/assignments/media-types/application/iges"))
    ("application/index" ("https://www.iana.org/assignments/media-types/application/index"))
    ("application/iotp" ("https://www.iana.org/assignments/media-types/application/IOTP"))
    ("application/ipfix" ("https://www.iana.org/assignments/media-types/application/ipfix"))
    ("application/ipp" ("https://www.iana.org/assignments/media-types/application/ipp"))
    ("application/isup" ("https://www.iana.org/assignments/media-types/application/ISUP"))
    ("application/javascript" ("https://www.iana.org/assignments/media-types/application/javascript"))
    ("application/jose" ("https://www.iana.org/assignments/media-types/application/jose"))
    ("application/json" ("https://www.iana.org/assignments/media-types/application/json"))
    ("application/json-seq" ("https://www.iana.org/assignments/media-types/application/json-seq"))
    ("application/jwt" ("https://www.iana.org/assignments/media-types/application/jwt"))
    ("application/link-format" ("https://www.iana.org/assignments/media-types/application/link-format"))
    ("application/lxf" ("https://www.iana.org/assignments/media-types/application/LXF"))
    ("application/mac-binhex40" ("https://www.iana.org/assignments/media-types/application/mac-binhex40"))
    ("application/macwriteii" ("https://www.iana.org/assignments/media-types/application/macwriteii"))
    ("application/marc" ("https://www.iana.org/assignments/media-types/application/marc"))
    ("application/mathematica" ("https://www.iana.org/assignments/media-types/application/mathematica"))
    ("application/mbox" ("https://www.iana.org/assignments/media-types/application/mbox"))
    ("application/mf4" ("https://www.iana.org/assignments/media-types/application/MF4"))
    ("application/mikey" ("https://www.iana.org/assignments/media-types/application/mikey"))
    ("application/moss-keys" ("https://www.iana.org/assignments/media-types/application/moss-keys"))
    ("application/moss-signature" ("https://www.iana.org/assignments/media-types/application/moss-signature"))
    ("application/mosskey-data" ("https://www.iana.org/assignments/media-types/application/mosskey-data"))
    ("application/mosskey-request" ("https://www.iana.org/assignments/media-types/application/mosskey-request"))
    ("application/mp21" ("https://www.iana.org/assignments/media-types/application/mp21"))
    ("application/mp4" ("https://www.iana.org/assignments/media-types/application/mp4"))
    ("application/mpeg4-generic" ("https://www.iana.org/assignments/media-types/application/mpeg4-generic"))
    ("application/mpeg4-iod" ("https://www.iana.org/assignments/media-types/application/mpeg4-iod"))
    ("application/mpeg4-iod-xmt" ("https://www.iana.org/assignments/media-types/application/mpeg4-iod-xmt"))
    ("application/msword" ("https://www.iana.org/assignments/media-types/application/msword"))
    ("application/mxf" ("https://www.iana.org/assignments/media-types/application/mxf"))
    ("application/nasdata" ("https://www.iana.org/assignments/media-types/application/nasdata"))
    ("application/news-checkgroups" ("https://www.iana.org/assignments/media-types/application/news-checkgroups"))
    ("application/news-groupinfo" ("https://www.iana.org/assignments/media-types/application/news-groupinfo"))
    ("application/news-transmission" ("https://www.iana.org/assignments/media-types/application/news-transmission"))
    ("application/nss" ("https://www.iana.org/assignments/media-types/application/nss"))
    ("application/ocsp-request" ("https://www.iana.org/assignments/media-types/application/ocsp-request"))
    ("application/ocsp-response" ("https://www.iana.org/assignments/media-types/application/ocsp-response"))
    ("application/octet-stream" ("https://www.iana.org/assignments/media-types/application/octet-stream"))
    ("application/oda" ("https://www.iana.org/assignments/media-types/application/ODA"))
    ("application/odx" ("https://www.iana.org/assignments/media-types/application/ODX"))
    ("application/ogg" ("https://www.iana.org/assignments/media-types/application/ogg"))
    ("application/oxps" ("https://www.iana.org/assignments/media-types/application/oxps"))
    ("application/pdf" ("https://www.iana.org/assignments/media-types/application/pdf"))
    ("application/pdx" ("https://www.iana.org/assignments/media-types/application/PDX"))
    ("application/pgp-encrypted" ("https://www.iana.org/assignments/media-types/application/pgp-encrypted"))
    ("application/pgp-signature" ("https://www.iana.org/assignments/media-types/application/pgp-signature"))
    ("application/pkcs10" ("https://www.iana.org/assignments/media-types/application/pkcs10"))
    ("application/pkcs7-mime" ("https://www.iana.org/assignments/media-types/application/pkcs7-mime"))
    ("application/pkcs7-signature" ("https://www.iana.org/assignments/media-types/application/pkcs7-signature"))
    ("application/pkcs8" ("https://www.iana.org/assignments/media-types/application/pkcs8"))
    ("application/pkcs12" ("https://www.iana.org/assignments/media-types/application/pkcs12"))
    ("application/pkix-attr-cert" ("https://www.iana.org/assignments/media-types/application/pkix-attr-cert"))
    ("application/pkix-cert" ("https://www.iana.org/assignments/media-types/application/pkix-cert"))
    ("application/pkix-crl" ("https://www.iana.org/assignments/media-types/application/pkix-crl"))
    ("application/pkix-pkipath" ("https://www.iana.org/assignments/media-types/application/pkix-pkipath"))
    ("application/pkixcmp" ("https://www.iana.org/assignments/media-types/application/pkixcmp"))
    ("application/postscript" ("https://www.iana.org/assignments/media-types/application/postscript"))
    ("application/qsig" ("https://www.iana.org/assignments/media-types/application/QSIG"))
    ("application/raptorfec" ("https://www.iana.org/assignments/media-types/application/raptorfec"))
    ("application/relax-ng-compact-syntax" ("https://www.iana.org/assignments/media-types/application/relax-ng-compact-syntax"))
    ("application/remote-printing" ("https://www.iana.org/assignments/media-types/application/remote-printing"))
    ("application/riscos" ("https://www.iana.org/assignments/media-types/application/riscos"))
    ("application/rpki-ghostbusters" ("https://www.iana.org/assignments/media-types/application/rpki-ghostbusters"))
    ("application/rpki-manifest" ("https://www.iana.org/assignments/media-types/application/rpki-manifest"))
    ("application/rpki-roa" ("https://www.iana.org/assignments/media-types/application/rpki-roa"))
    ("application/rpki-updown" ("https://www.iana.org/assignments/media-types/application/rpki-updown"))
    ("application/rtf" ("https://www.iana.org/assignments/media-types/application/rtf"))
    ("application/rtploopback" ("https://www.iana.org/assignments/media-types/application/rtploopback"))
    ("application/rtx" ("https://www.iana.org/assignments/media-types/application/rtx"))
    ("application/scvp-cv-request" ("https://www.iana.org/assignments/media-types/application/scvp-cv-request"))
    ("application/scvp-cv-response" ("https://www.iana.org/assignments/media-types/application/scvp-cv-response"))
    ("application/scvp-vp-request" ("https://www.iana.org/assignments/media-types/application/scvp-vp-request"))
    ("application/scvp-vp-response" ("https://www.iana.org/assignments/media-types/application/scvp-vp-response"))
    ("application/sdp" ("https://www.iana.org/assignments/media-types/application/sdp"))
    ("application/sep-exi" ("https://www.iana.org/assignments/media-types/application/sep-exi"))
    ("application/session-info" ("https://www.iana.org/assignments/media-types/application/session-info"))
    ("application/set-payment" ("https://www.iana.org/assignments/media-types/application/set-payment"))
    ("application/set-payment-initiation" ("https://www.iana.org/assignments/media-types/application/set-payment-initiation"))
    ("application/set-registration" ("https://www.iana.org/assignments/media-types/application/set-registration"))
    ("application/set-registration-initiation" ("https://www.iana.org/assignments/media-types/application/set-registration-initiation"))
    ("application/sgml" ("https://www.iana.org/assignments/media-types/application/SGML"))
    ("application/sgml-open-catalog" ("https://www.iana.org/assignments/media-types/application/sgml-open-catalog"))
    ("application/sieve" ("https://www.iana.org/assignments/media-types/application/sieve"))
    ("application/simple-message-summary" ("https://www.iana.org/assignments/media-types/application/simple-message-summary"))
    ("application/simplesymbolcontainer" ("https://www.iana.org/assignments/media-types/application/simpleSymbolContainer"))
    ("application/slate" ("https://www.iana.org/assignments/media-types/application/slate"))
    ("application/smpte336m" ("https://www.iana.org/assignments/media-types/application/smpte336m"))
    ("application/sql" ("https://www.iana.org/assignments/media-types/application/sql"))
    ("application/srgs" ("https://www.iana.org/assignments/media-types/application/srgs"))
    ("application/tamp-apex-update" ("https://www.iana.org/assignments/media-types/application/tamp-apex-update"))
    ("application/tamp-apex-update-confirm" ("https://www.iana.org/assignments/media-types/application/tamp-apex-update-confirm"))
    ("application/tamp-community-update" ("https://www.iana.org/assignments/media-types/application/tamp-community-update"))
    ("application/tamp-community-update-confirm" ("https://www.iana.org/assignments/media-types/application/tamp-community-update-confirm"))
    ("application/tamp-error" ("https://www.iana.org/assignments/media-types/application/tamp-error"))
    ("application/tamp-sequence-adjust" ("https://www.iana.org/assignments/media-types/application/tamp-sequence-adjust"))
    ("application/tamp-sequence-adjust-confirm" ("https://www.iana.org/assignments/media-types/application/tamp-sequence-adjust-confirm"))
    ("application/tamp-status-query" ("https://www.iana.org/assignments/media-types/application/tamp-status-query"))
    ("application/tamp-status-response" ("https://www.iana.org/assignments/media-types/application/tamp-status-response"))
    ("application/tamp-update" ("https://www.iana.org/assignments/media-types/application/tamp-update"))
    ("application/tamp-update-confirm" ("https://www.iana.org/assignments/media-types/application/tamp-update-confirm"))
    ("application/timestamp-query" ("https://www.iana.org/assignments/media-types/application/timestamp-query"))
    ("application/timestamp-reply" ("https://www.iana.org/assignments/media-types/application/timestamp-reply"))
    ("application/timestamped-data" ("https://www.iana.org/assignments/media-types/application/timestamped-data"))
    ("application/tve-trigger" ("https://www.iana.org/assignments/media-types/application/tve-trigger"))
    ("application/ulpfec" ("https://www.iana.org/assignments/media-types/application/ulpfec"))
    ("application/vemmi" ("https://www.iana.org/assignments/media-types/application/vemmi"))
    ("application/vq-rtcpxr" ("https://www.iana.org/assignments/media-types/application/vq-rtcpxr"))
    ("application/whoispp-query" ("https://www.iana.org/assignments/media-types/application/whoispp-query"))
    ("application/whoispp-response" ("https://www.iana.org/assignments/media-types/application/whoispp-response"))
    ("application/wita" ("https://www.iana.org/assignments/media-types/application/wita"))
    ("application/x-www-form-urlencoded" ("https://www.iana.org/assignments/media-types/application/x-www-form-urlencoded"))
    ("application/x400-bp" ("https://www.iana.org/assignments/media-types/application/x400-bp"))
    ("application/xml" ("https://www.iana.org/assignments/media-types/application/xml"))
    ("application/xml-dtd" ("https://www.iana.org/assignments/media-types/application/xml-dtd"))
    ("application/xml-external-parsed-entity" ("https://www.iana.org/assignments/media-types/application/xml-external-parsed-entity"))
    ("application/yang" ("https://www.iana.org/assignments/media-types/application/yang"))
    ("application/zip" ("https://www.iana.org/assignments/media-types/application/zip"))
    ("application/zlib" ("https://www.iana.org/assignments/media-types/application/zlib"))
    ("audio/1d-interleaved-parityfec" ("https://www.iana.org/assignments/media-types/audio/1d-interleaved-parityfec"))
    ("audio/32kadpcm" ("https://www.iana.org/assignments/media-types/audio/32kadpcm"))
    ("audio/3gpp" ("https://www.iana.org/assignments/media-types/audio/3gpp"))
    ("audio/3gpp2" ("https://www.iana.org/assignments/media-types/audio/3gpp2"))
    ("audio/ac3" ("https://www.iana.org/assignments/media-types/audio/ac3"))
    ("audio/amr" ("https://www.iana.org/assignments/media-types/audio/AMR"))
    ("audio/amr-wb" ("https://www.iana.org/assignments/media-types/audio/AMR-WB"))
    ("audio/aptx" ("https://www.iana.org/assignments/media-types/audio/aptx"))
    ("audio/asc" ("https://www.iana.org/assignments/media-types/audio/asc"))
    ("audio/atrac-advanced-lossless" ("https://www.iana.org/assignments/media-types/audio/ATRAC-ADVANCED-LOSSLESS"))
    ("audio/atrac-x" ("https://www.iana.org/assignments/media-types/audio/ATRAC-X"))
    ("audio/atrac3" ("https://www.iana.org/assignments/media-types/audio/ATRAC3"))
    ("audio/basic" ("https://www.iana.org/assignments/media-types/audio/basic"))
    ("audio/bv16" ("https://www.iana.org/assignments/media-types/audio/BV16"))
    ("audio/bv32" ("https://www.iana.org/assignments/media-types/audio/BV32"))
    ("audio/clearmode" ("https://www.iana.org/assignments/media-types/audio/clearmode"))
    ("audio/cn" ("https://www.iana.org/assignments/media-types/audio/CN"))
    ("audio/dat12" ("https://www.iana.org/assignments/media-types/audio/DAT12"))
    ("audio/dls" ("https://www.iana.org/assignments/media-types/audio/dls"))
    ("audio/dsr-es201108" ("https://www.iana.org/assignments/media-types/audio/dsr-es201108"))
    ("audio/dsr-es202050" ("https://www.iana.org/assignments/media-types/audio/dsr-es202050"))
    ("audio/dsr-es202211" ("https://www.iana.org/assignments/media-types/audio/dsr-es202211"))
    ("audio/dsr-es202212" ("https://www.iana.org/assignments/media-types/audio/dsr-es202212"))
    ("audio/dv" ("https://www.iana.org/assignments/media-types/audio/DV"))
    ("audio/dvi4" ("https://www.iana.org/assignments/media-types/audio/DVI4"))
    ("audio/eac3" ("https://www.iana.org/assignments/media-types/audio/eac3"))
    ("audio/encaprtp" ("https://www.iana.org/assignments/media-types/audio/encaprtp"))
    ("audio/evrc" ("https://www.iana.org/assignments/media-types/audio/EVRC"))
    ("audio/evrc-qcp" ("https://www.iana.org/assignments/media-types/audio/EVRC-QCP"))
    ("audio/evrc0" ("https://www.iana.org/assignments/media-types/audio/EVRC0"))
    ("audio/evrc1" ("https://www.iana.org/assignments/media-types/audio/EVRC1"))
    ("audio/evrcb" ("https://www.iana.org/assignments/media-types/audio/EVRCB"))
    ("audio/evrcb0" ("https://www.iana.org/assignments/media-types/audio/EVRCB0"))
    ("audio/evrcb1" ("https://www.iana.org/assignments/media-types/audio/EVRCB1"))
    ("audio/evrcnw" ("https://www.iana.org/assignments/media-types/audio/EVRCNW"))
    ("audio/evrcnw0" ("https://www.iana.org/assignments/media-types/audio/EVRCNW0"))
    ("audio/evrcnw1" ("https://www.iana.org/assignments/media-types/audio/EVRCNW1"))
    ("audio/evrcwb" ("https://www.iana.org/assignments/media-types/audio/EVRCWB"))
    ("audio/evrcwb0" ("https://www.iana.org/assignments/media-types/audio/EVRCWB0"))
    ("audio/evrcwb1" ("https://www.iana.org/assignments/media-types/audio/EVRCWB1"))
    ("audio/evs" ("https://www.iana.org/assignments/media-types/audio/EVS"))
    ("audio/example" ("https://www.iana.org/assignments/media-types/audio/example"))
    ("audio/fwdred" ("https://www.iana.org/assignments/media-types/audio/fwdred"))
    ("audio/g711-0" ("https://www.iana.org/assignments/media-types/audio/G711-0"))
    ("audio/g719" ("https://www.iana.org/assignments/media-types/audio/G719"))
    ("audio/g7221" ("https://www.iana.org/assignments/media-types/audio/G7221"))
    ("audio/g722" ("https://www.iana.org/assignments/media-types/audio/G722"))
    ("audio/g723" ("https://www.iana.org/assignments/media-types/audio/G723"))
    ("audio/g726-16" ("https://www.iana.org/assignments/media-types/audio/G726-16"))
    ("audio/g726-24" ("https://www.iana.org/assignments/media-types/audio/G726-24"))
    ("audio/g726-32" ("https://www.iana.org/assignments/media-types/audio/G726-32"))
    ("audio/g726-40" ("https://www.iana.org/assignments/media-types/audio/G726-40"))
    ("audio/g728" ("https://www.iana.org/assignments/media-types/audio/G728"))
    ("audio/g729" ("https://www.iana.org/assignments/media-types/audio/G729"))
    ("audio/g729d" ("https://www.iana.org/assignments/media-types/audio/G729D"))
    ("audio/g729e" ("https://www.iana.org/assignments/media-types/audio/G729E"))
    ("audio/gsm" ("https://www.iana.org/assignments/media-types/audio/GSM"))
    ("audio/gsm-efr" ("https://www.iana.org/assignments/media-types/audio/GSM-EFR"))
    ("audio/gsm-hr-08" ("https://www.iana.org/assignments/media-types/audio/GSM-HR-08"))
    ("audio/ilbc" ("https://www.iana.org/assignments/media-types/audio/iLBC"))
    ("audio/l8" ("https://www.iana.org/assignments/media-types/audio/L8"))
    ("audio/l16" ("https://www.iana.org/assignments/media-types/audio/L16"))
    ("audio/l20" ("https://www.iana.org/assignments/media-types/audio/L20"))
    ("audio/l24" ("https://www.iana.org/assignments/media-types/audio/L24"))
    ("audio/lpc" ("https://www.iana.org/assignments/media-types/audio/LPC"))
    ("audio/mobile-xmf" ("https://www.iana.org/assignments/media-types/audio/mobile-xmf"))
    ("audio/mpa" ("https://www.iana.org/assignments/media-types/audio/MPA"))
    ("audio/mp4" ("https://www.iana.org/assignments/media-types/audio/mp4"))
    ("audio/mp4a-latm" ("https://www.iana.org/assignments/media-types/audio/MP4A-LATM"))
    ("audio/mpa-robust" ("https://www.iana.org/assignments/media-types/audio/mpa-robust"))
    ("audio/mpeg" ("https://www.iana.org/assignments/media-types/audio/mpeg"))
    ("audio/mpeg4-generic" ("https://www.iana.org/assignments/media-types/audio/mpeg4-generic"))
    ("audio/ogg" ("https://www.iana.org/assignments/media-types/audio/ogg"))
    ("audio/opus" ("https://www.iana.org/assignments/media-types/audio/opus"))
    ("audio/pcma" ("https://www.iana.org/assignments/media-types/audio/PCMA"))
    ("audio/pcma-wb" ("https://www.iana.org/assignments/media-types/audio/PCMA-WB"))
    ("audio/pcmu" ("https://www.iana.org/assignments/media-types/audio/PCMU"))
    ("audio/pcmu-wb" ("https://www.iana.org/assignments/media-types/audio/PCMU-WB"))
    ("audio/raptorfec" ("https://www.iana.org/assignments/media-types/audio/raptorfec"))
    ("audio/red" ("https://www.iana.org/assignments/media-types/audio/RED"))
    ("audio/rtp-enc-aescm128" ("https://www.iana.org/assignments/media-types/audio/rtp-enc-aescm128"))
    ("audio/rtploopback" ("https://www.iana.org/assignments/media-types/audio/rtploopback"))
    ("audio/rtp-midi" ("https://www.iana.org/assignments/media-types/audio/rtp-midi"))
    ("audio/rtx" ("https://www.iana.org/assignments/media-types/audio/rtx"))
    ("audio/smv" ("https://www.iana.org/assignments/media-types/audio/SMV"))
    ("audio/smv0" ("https://www.iana.org/assignments/media-types/audio/SMV0"))
    ("audio/smv-qcp" ("https://www.iana.org/assignments/media-types/audio/SMV-QCP"))
    ("audio/sp-midi" ("https://www.iana.org/assignments/media-types/audio/sp-midi"))
    ("audio/speex" ("https://www.iana.org/assignments/media-types/audio/speex"))
    ("audio/t140c" ("https://www.iana.org/assignments/media-types/audio/t140c"))
    ("audio/t38" ("https://www.iana.org/assignments/media-types/audio/t38"))
    ("audio/telephone-event" ("https://www.iana.org/assignments/media-types/audio/telephone-event"))
    ("audio/tone" ("https://www.iana.org/assignments/media-types/audio/tone"))
    ("audio/uemclip" ("https://www.iana.org/assignments/media-types/audio/UEMCLIP"))
    ("audio/ulpfec" ("https://www.iana.org/assignments/media-types/audio/ulpfec"))
    ("audio/vdvi" ("https://www.iana.org/assignments/media-types/audio/VDVI"))
    ("audio/vmr-wb" ("https://www.iana.org/assignments/media-types/audio/VMR-WB"))
    ("audio/vorbis" ("https://www.iana.org/assignments/media-types/audio/vorbis"))
    ("audio/vorbis-config" ("https://www.iana.org/assignments/media-types/audio/vorbis-config"))
    ("image/cgm" ("https://www.iana.org/assignments/media-types/image/cgm"))
    ("image/example" ("https://www.iana.org/assignments/media-types/image/example"))
    ("image/fits" ("https://www.iana.org/assignments/media-types/image/fits"))
    ("image/g3fax" ("https://www.iana.org/assignments/media-types/image/g3fax"))
    ("image/jp2" ("https://www.iana.org/assignments/media-types/image/jp2"))
    ("image/jpm" ("https://www.iana.org/assignments/media-types/image/jpm"))
    ("image/jpx" ("https://www.iana.org/assignments/media-types/image/jpx"))
    ("image/naplps" ("https://www.iana.org/assignments/media-types/image/naplps"))
    ("image/png" ("https://www.iana.org/assignments/media-types/image/png"))
    ("image/pwg-raster" ("https://www.iana.org/assignments/media-types/image/pwg-raster"))
    ("image/t38" ("https://www.iana.org/assignments/media-types/image/t38"))
    ("image/tiff" ("https://www.iana.org/assignments/media-types/image/tiff"))
    ("image/tiff-fx" ("https://www.iana.org/assignments/media-types/image/tiff-fx"))
    ("message/cpim" ("https://www.iana.org/assignments/media-types/message/CPIM"))
    ("message/delivery-status" ("https://www.iana.org/assignments/media-types/message/delivery-status"))
    ("message/disposition-notification" ("https://www.iana.org/assignments/media-types/message/disposition-notification"))
    ("message/example" ("https://www.iana.org/assignments/media-types/message/example"))
    ("message/feedback-report" ("https://www.iana.org/assignments/media-types/message/feedback-report"))
    ("message/global" ("https://www.iana.org/assignments/media-types/message/global"))
    ("message/global-delivery-status" ("https://www.iana.org/assignments/media-types/message/global-delivery-status"))
    ("message/global-disposition-notification" ("https://www.iana.org/assignments/media-types/message/global-disposition-notification"))
    ("message/global-headers" ("https://www.iana.org/assignments/media-types/message/global-headers"))
    ("message/http" ("https://www.iana.org/assignments/media-types/message/http"))
    ("message/s-http" ("https://www.iana.org/assignments/media-types/message/s-http"))
    ("message/sip" ("https://www.iana.org/assignments/media-types/message/sip"))
    ("message/sipfrag" ("https://www.iana.org/assignments/media-types/message/sipfrag"))
    ("message/tracking-status" ("https://www.iana.org/assignments/media-types/message/tracking-status"))
    ("model/example" ("https://www.iana.org/assignments/media-types/model/example"))
    ("model/iges" ("https://www.iana.org/assignments/media-types/model/iges"))
    ("model/x3d-vrml" ("https://www.iana.org/assignments/media-types/model/x3d-vrml"))
    ("multipart/appledouble" ("https://www.iana.org/assignments/media-types/multipart/appledouble"))
    ("multipart/byteranges" ("https://www.iana.org/assignments/media-types/multipart/byteranges"))
    ("multipart/encrypted" ("https://www.iana.org/assignments/media-types/multipart/encrypted"))
    ("multipart/example" ("https://www.iana.org/assignments/media-types/multipart/example"))
    ("multipart/form-data" ("https://www.iana.org/assignments/media-types/multipart/form-data"))
    ("multipart/header-set" ("https://www.iana.org/assignments/media-types/multipart/header-set"))
    ("multipart/related" ("https://www.iana.org/assignments/media-types/multipart/related"))
    ("multipart/report" ("https://www.iana.org/assignments/media-types/multipart/report"))
    ("multipart/signed" ("https://www.iana.org/assignments/media-types/multipart/signed"))
    ("multipart/voice-message" ("https://www.iana.org/assignments/media-types/multipart/voice-message"))
    ("multipart/x-mixed-replace" ("https://www.iana.org/assignments/media-types/multipart/x-mixed-replace"))
    ("text/1d-interleaved-parityfec" ("https://www.iana.org/assignments/media-types/text/1d-interleaved-parityfec"))
    ("text/cache-manifest" ("https://www.iana.org/assignments/media-types/text/cache-manifest"))
    ("text/calendar" ("https://www.iana.org/assignments/media-types/text/calendar"))
    ("text/css" ("https://www.iana.org/assignments/media-types/text/css"))
    ("text/csv" ("https://www.iana.org/assignments/media-types/text/csv"))
    ("text/csv-schema" ("https://www.iana.org/assignments/media-types/text/csv-schema"))
    ("text/dns" ("https://www.iana.org/assignments/media-types/text/dns"))
    ("text/encaprtp" ("https://www.iana.org/assignments/media-types/text/encaprtp"))
    ("text/example" ("https://www.iana.org/assignments/media-types/text/example"))
    ("text/fwdred" ("https://www.iana.org/assignments/media-types/text/fwdred"))
    ("text/grammar-ref-list" ("https://www.iana.org/assignments/media-types/text/grammar-ref-list"))
    ("text/html" ("https://www.iana.org/assignments/media-types/text/html"))
    ("text/jcr-cnd" ("https://www.iana.org/assignments/media-types/text/jcr-cnd"))
    ("text/markdown" ("https://www.iana.org/assignments/media-types/text/markdown"))
    ("text/mizar" ("https://www.iana.org/assignments/media-types/text/mizar"))
    ("text/n3" ("https://www.iana.org/assignments/media-types/text/n3"))
    ("text/parameters" ("https://www.iana.org/assignments/media-types/text/parameters"))
    ("text/provenance-notation" ("https://www.iana.org/assignments/media-types/text/provenance-notation"))
    ("text/raptorfec" ("https://www.iana.org/assignments/media-types/text/raptorfec"))
    ("text/red" ("https://www.iana.org/assignments/media-types/text/RED"))
    ("text/rfc822-headers" ("https://www.iana.org/assignments/media-types/text/rfc822-headers"))
    ("text/rtf" ("https://www.iana.org/assignments/media-types/text/rtf"))
    ("text/rtp-enc-aescm128" ("https://www.iana.org/assignments/media-types/text/rtp-enc-aescm128"))
    ("text/rtploopback" ("https://www.iana.org/assignments/media-types/text/rtploopback"))
    ("text/rtx" ("https://www.iana.org/assignments/media-types/text/rtx"))
    ("text/sgml" ("https://www.iana.org/assignments/media-types/text/SGML"))
    ("text/t140" ("https://www.iana.org/assignments/media-types/text/t140"))
    ("text/tab-separated-values" ("https://www.iana.org/assignments/media-types/text/tab-separated-values"))
    ("text/troff" ("https://www.iana.org/assignments/media-types/text/troff"))
    ("text/turtle" ("https://www.iana.org/assignments/media-types/text/turtle"))
    ("text/ulpfec" ("https://www.iana.org/assignments/media-types/text/ulpfec"))
    ("text/uri-list" ("https://www.iana.org/assignments/media-types/text/uri-list"))
    ("text/vcard" ("https://www.iana.org/assignments/media-types/text/vcard"))
    ("text/xml" ("https://www.iana.org/assignments/media-types/text/xml"))
    ("text/xml-external-parsed-entity" ("https://www.iana.org/assignments/media-types/text/xml-external-parsed-entity"))
    ("video/1d-interleaved-parityfec" ("https://www.iana.org/assignments/media-types/video/1d-interleaved-parityfec"))
    ("video/3gpp" ("https://www.iana.org/assignments/media-types/video/3gpp"))
    ("video/3gpp2" ("https://www.iana.org/assignments/media-types/video/3gpp2"))
    ("video/3gpp-tt" ("https://www.iana.org/assignments/media-types/video/3gpp-tt"))
    ("video/bmpeg" ("https://www.iana.org/assignments/media-types/video/BMPEG"))
    ("video/bt656" ("https://www.iana.org/assignments/media-types/video/BT656"))
    ("video/celb" ("https://www.iana.org/assignments/media-types/video/CelB"))
    ("video/dv" ("https://www.iana.org/assignments/media-types/video/DV"))
    ("video/encaprtp" ("https://www.iana.org/assignments/media-types/video/encaprtp"))
    ("video/example" ("https://www.iana.org/assignments/media-types/video/example"))
    ("video/h261" ("https://www.iana.org/assignments/media-types/video/H261"))
    ("video/h263" ("https://www.iana.org/assignments/media-types/video/H263"))
    ("video/h263-1998" ("https://www.iana.org/assignments/media-types/video/H263-1998"))
    ("video/h263-2000" ("https://www.iana.org/assignments/media-types/video/H263-2000"))
    ("video/h264" ("https://www.iana.org/assignments/media-types/video/H264"))
    ("video/h264-rcdo" ("https://www.iana.org/assignments/media-types/video/H264-RCDO"))
    ("video/h264-svc" ("https://www.iana.org/assignments/media-types/video/H264-SVC"))
    ("video/h265" ("https://www.iana.org/assignments/media-types/video/H265"))
    ("video/jpeg" ("https://www.iana.org/assignments/media-types/video/JPEG"))
    ("video/jpeg2000" ("https://www.iana.org/assignments/media-types/video/jpeg2000"))
    ("video/mj2" ("https://www.iana.org/assignments/media-types/video/mj2"))
    ("video/mp1s" ("https://www.iana.org/assignments/media-types/video/MP1S"))
    ("video/mp2p" ("https://www.iana.org/assignments/media-types/video/MP2P"))
    ("video/mp2t" ("https://www.iana.org/assignments/media-types/video/MP2T"))
    ("video/mp4" ("https://www.iana.org/assignments/media-types/video/mp4"))
    ("video/mp4v-es" ("https://www.iana.org/assignments/media-types/video/MP4V-ES"))
    ("video/mpv" ("https://www.iana.org/assignments/media-types/video/MPV"))
    ("video/mpeg4-generic" ("https://www.iana.org/assignments/media-types/video/mpeg4-generic"))
    ("video/nv" ("https://www.iana.org/assignments/media-types/video/nv"))
    ("video/ogg" ("https://www.iana.org/assignments/media-types/video/ogg"))
    ("video/pointer" ("https://www.iana.org/assignments/media-types/video/pointer"))
    ("video/quicktime" ("https://www.iana.org/assignments/media-types/video/quicktime"))
    ("video/raptorfec" ("https://www.iana.org/assignments/media-types/video/raptorfec"))
    ("video/rtp-enc-aescm128" ("https://www.iana.org/assignments/media-types/video/rtp-enc-aescm128"))
    ("video/rtploopback" ("https://www.iana.org/assignments/media-types/video/rtploopback"))
    ("video/rtx" ("https://www.iana.org/assignments/media-types/video/rtx"))
    ("video/smpte292m" ("https://www.iana.org/assignments/media-types/video/SMPTE292M"))
    ("video/ulpfec" ("https://www.iana.org/assignments/media-types/video/ulpfec"))
    ("video/vc1" ("https://www.iana.org/assignments/media-types/video/vc1"))
    ("video/vp8" ("https://www.iana.org/assignments/media-types/video/VP8"))))

(defun consult-http-statuses ()
  "Doc."
  (interactive)
  (insert
   (consult--read
    (cl-loop for (name (status desc)) in http-status
             collect (propertize (format "%s %s %s"
                                         (propertize status 'face 'consult-async-option)
                                         name
                                         (propertize desc 'face 'font-lock-comment-face))
                                 'consult--candidate status))
    :prompt "HTTP Status: "
    :category 'consult-grep
    :lookup #'consult--lookup-candidate)))

;; (with-eval-after-load 'embark-consult
;;   (remove-hook 'embark-collect-mode-hook
;;                #'consult-preview-at-point-mode))

(defun consult-http-headers ()
  "Doc."
  (interactive)
  (insert
   (consult--read
    (cl-loop for (name (desc)) in http-headers
             collect (propertize (format "%s %s"
                                         name
                                         (propertize desc 'face 'font-lock-comment-face))
                                 'consult--candidate name))
    :prompt "HTTP Header: "
    :category 'consult-grep
    :lookup #'consult--lookup-candidate)))

(defun consult-media-types (arg)
  "Doc.  ARG: if negative - browse url."
  (interactive "p")
  (let ((cmd (if (cl-minusp arg) #'browse-url #'insert))
        (candidate (if (cl-minusp arg) #'cdr #'car)))
    (funcall
     cmd
     (consult--read
        (cl-loop for (name (desc)) in media-types
                 collect (propertize (format "%s %s"
                                             name
                                             (propertize desc 'face 'font-lock-comment-face))
                                     'consult--candidate (funcall candidate (cons name desc))))
        :prompt "HTTP Content-Type: "
        :category 'consult-grep
        :lookup #'consult--lookup-candidate))))

(define-key help-map (kbd "0") #'consult-http-statuses)
(define-key help-map (kbd "/") #'consult-media-types)
(define-key help-map (kbd "=") #'consult-http-headers)

(provide 'my-consult-http-things)
;;; my-consult-http-things.el ends here
